development:

  aws_key: AKIAILW6GM4ZXAFMTJYA
  aws_secret: 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
  aws_bucket: influx-dev1

production:

    aws_key: AKIAILW6GM4ZXAFMTJYA
    aws_secret: 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
    aws_bucket: influx-dev2
